name: runtests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'

      - name: Cache Julia packages
        uses: julia-actions/cache@v1

      - name: Build Julia packages
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1